name: Check filenames

on:
  push:
    paths:
      - 'masks/**'
      - 'tools/check_filename.py'
      - '.github/workflows/check_filename.yml'
  pull_request:
    paths:
      - 'masks/**'
      - 'tools/check_filename.py'
      - '.github/workflows/check_filename.yml'

jobs:
  stat:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Amount Done
      run: |
        python tools/check_filename.py
